### ISSUE TITLE
bvimgrep doesn't seem to work with Vim 8.0.0066?

### ISSUE THREAD

**Issue by for-coursera** [chrisbra/vim-mq-patches#1]
Below is the extract from the Homebrew build process:

    patching file runtime/doc/quickfix.txt
    Hunk #1 succeeded at 745 (offset 37 lines).
    patching file src/buffer.c
    Hunk #1 succeeded at 2669 (offset 217 lines).
    patching file src/ex_cmds.h
    patching file src/ex_docmd.c
    Hunk #1 succeeded at 2904 (offset 40 lines).
    Hunk #2 succeeded at 4135 (offset 44 lines).
    Hunk #3 succeeded at 4803 (offset 49 lines).
    patching file src/proto/buffer.pro
    Hunk #1 succeeded at 21 (offset 2 lines).
    patching file src/proto/screen.pro
    patching file src/quickfix.c
    Hunk #1 succeeded at 3920 (offset 347 lines).
    Hunk #2 succeeded at 3940 (offset 347 lines).
    Hunk #3 succeeded at 3956 (offset 347 lines).
    Hunk #4 succeeded at 3972 (offset 347 lines).
    Hunk #5 succeeded at 4029 (offset 347 lines).
    Hunk #6 succeeded at 4083 (offset 347 lines).
    Hunk #7 FAILED at 4205.
    Hunk #8 succeeded at 4306 (offset 354 lines).
    Hunk #9 succeeded at 4368 (offset 354 lines).
    1 out of 9 hunks FAILED -- saving rejects to file src/quickfix.c.rej
    patching file src/screen.c
    Hunk #1 succeeded at 983 (offset 19 lines).
    patching file src/testdir/test_bvimgrep.vim
    Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/vim--patch-20161108-35283-1c30irn/bvimgrep.patch

**Comment by chrisbra** [comment]
Am 2016-11-08 06:32, schrieb for-coursera:

> Below is the extract from the Homebrew build process:
> 
> patching file runtime/doc/quickfix.txt
> Hunk #1 succeeded at 745 (offset 37 lines).
> patching file src/buffer.c
> Hunk #1 succeeded at 2669 (offset 217 lines).
> patching file src/ex_cmds.h
> patching file src/ex_docmd.c
> Hunk #1 succeeded at 2904 (offset 40 lines).
> Hunk #2 succeeded at 4135 (offset 44 lines).
> Hunk #3 succeeded at 4803 (offset 49 lines).
> patching file src/proto/buffer.pro
> Hunk #1 succeeded at 21 (offset 2 lines).
> patching file src/proto/screen.pro
> patching file src/quickfix.c
> Hunk #1 succeeded at 3920 (offset 347 lines).
> Hunk #2 succeeded at 3940 (offset 347 lines).
> Hunk #3 succeeded at 3956 (offset 347 lines).
> Hunk #4 succeeded at 3972 (offset 347 lines).
> Hunk #5 succeeded at 4029 (offset 347 lines).
> Hunk #6 succeeded at 4083 (offset 347 lines).
> Hunk #7 FAILED at 4205.
> Hunk #8 succeeded at 4306 (offset 354 lines).
> Hunk #9 succeeded at 4368 (offset 354 lines).
> 1 out of 9 hunks FAILED -- saving rejects to file src/quickfix.c.rej
> patching file src/screen.c
> Hunk #1 succeeded at 983 (offset 19 lines).
> patching file src/testdir/test_bvimgrep.vim
> Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i
> /private/tmp/vim--patch-20161108-35283-1c30irn/bvimgrep.patch

Yeah something like this was about to happen, since I haven't kept the 
patch up to date.
I'll look into it and will fix it.

BTW: do you happen to know, which official Vim patch broke it?

Best,
Christian

**Comment by for-coursera** [comment]
No, sorry, I wasn't a regular updater, just moved now to vim8 from vim7.4.

Thanks for your support!

**Comment by for-coursera** [comment]
Happened once again, now doesn't updates to 8.0.1100_1 :)

    patching file runtime/doc/quickfix.txt
    Hunk #1 succeeded at 780 (offset 18 lines).
    patching file src/buffer.c
    Hunk #1 succeeded at 2751 (offset 49 lines).
    patching file src/ex_cmds.h
    Hunk #1 succeeded at 187 (offset 2 lines).
    Hunk #2 succeeded at 232 (offset 2 lines).
    patching file src/ex_docmd.c
    Hunk #1 succeeded at 2894 (offset -69 lines).
    Hunk #2 succeeded at 4159 (offset -66 lines).
    Hunk #3 succeeded at 4883 (offset -53 lines).
    patching file src/proto/buffer.pro
    Hunk #1 succeeded at 23 (offset 2 lines).
    patching file src/proto/screen.pro
    Hunk #1 succeeded at 15 with fuzz 2 (offset 1 line).
    patching file src/quickfix.c
    Hunk #1 succeeded at 3984 (offset 11 lines).
    Hunk #2 succeeded at 4004 (offset 11 lines).
    Hunk #3 succeeded at 4020 (offset 11 lines).
    Hunk #4 succeeded at 4036 (offset 11 lines).
    Hunk #5 succeeded at 4055 (offset 11 lines).
    Hunk #6 FAILED at 4098.
    Hunk #7 succeeded at 4156 (offset 11 lines).
    Hunk #8 succeeded at 4379 (offset 12 lines).
    Hunk #9 succeeded at 4443 (offset 12 lines).
    1 out of 9 hunks FAILED -- saving rejects to file src/quickfix.c.rej
    patching file src/screen.c
    Hunk #1 succeeded at 1055 (offset 85 lines).
    patching file src/testdir/Make_all.mak
    Hunk #1 succeeded at 117 (offset -24 lines).
    patching file src/testdir/test_bvimgrep.vim
    Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/vim--patch-20170920-41167-1ilmw51/bvimgrep

**Comment by chrisbra** [comment]
thanks for noticing me, will update it

**Comment by chrisbra** [comment]
should work now again

**Comment by for-coursera** [comment]
Seems like working, thanks!
